### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by centuryrehab** [clemsau/telegram-gpt#2]
My key has never been used. Verified it via portal.

Any ideas?

root@Javis-1:~/telegram-gpt/src# python3 bot.py
No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/telegram/ext/_application.py", line 1104, in process_update
    await coroutine
  File "/usr/local/lib/python3.10/dist-packages/telegram/ext/_handler.py", line 141, in handle_update
    return await self.callback(update, context)
  File "/root/telegram-gpt/src/handlers.py", line 28, in message_handler
    answer: str = await openai_instance.complete(message)
  File "/root/telegram-gpt/src/openai_utils.py", line 22, in complete
    response = await openai.ChatCompletion.acreate(
  File "/usr/local/lib/python3.10/dist-packages/openai/api_resources/chat_completion.py", line 45, in acreate
    return await super().acreate(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/openai/api_resources/abstract/engine_api_resource.py", line 217, in acreate
    response, _, api_key = await requestor.arequest(
  File "/usr/local/lib/python3.10/dist-packages/openai/api_requestor.py", line 310, in arequest
    resp, got_stream = await self._interpret_async_response(result, stream)
  File "/usr/local/lib/python3.10/dist-packages/openai/api_requestor.py", line 645, in _interpret_async_response
    self._interpret_response_line(
  File "/usr/local/lib/python3.10/dist-packages/openai/api_requestor.py", line 682, in _interpret_response_line
    raise self.handle_error_response(
openai.error.RateLimitError: You exceeded your current quota, please check your plan and billing details.

**Comment by clemsau** [comment]
Checkout the usage of your API key on the OpenAI platform.

One possible issue is that you did setup your API more than one month ago, and you were running on the free 18$ granted when using the API key for the first time. These free credits expires after one month. After that, you have to use your card info in the OpenAi dashboard.

**Comment by clemsau** [comment]
I assume that you solved your issue with my previous comment. I close the issue.
